#!/usr/bin/env php
<?php
if (php_sapi_name() !== 'cli') {
	return;
}
define('ROOT_DIR', __DIR__);
require 'core/main/Kernel.php';
core\main\Kernel::registerAutoloader();

$console = \cli\Console::getInstance($argc, $argv);
$console->handle();

