<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return [
	'core\\' => [$baseDir . '/core/'],
	'modules\\' => [$baseDir . '/modules/'],
	'cli\\' => [$baseDir . '/cli/'],
	'api\\' => [$baseDir . '/api/'],
];
